spring.application.name=ecommerce_backend

# 1. Configuración de conexión a tu Debian (MariaDB)
spring.datasource.url=jdbc:mariadb://10.165.130.29:3306/ecommerce
spring.datasource.username=capibaras
spring.datasource.password=1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# 2. Configuración de Hibernate (Dialecto para MariaDB)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# 3. Comportamiento de la Base de Datos
# PONEMOS "none" PARA QUE SPRING NO BORRE NI MODIFIQUE TUS TABLAS
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 4. Puerto del servidor Spring Boot
server.port=8080